# Generated by Django 3.2.9 on 2021-11-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_link',
            field=models.URLField(max_length=400),
        ),
    ]
