# Generated by Django 3.2.8 on 2021-10-31 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_text',
            new_name='note',
        ),
    ]
