# Generated by Django 3.2.8 on 2021-10-31 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_note_text_note_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='note_text',
        ),
    ]
